name: Deploy on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create the ".env" file with Environment Variables
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: .env
          envkey_REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          envkey_REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          envkey_REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          envkey_REACT_APP_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          envkey_REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Prepare environment with Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Project Dependencies with Yarn
        run: yarn install

      - name: Project Build with Yarn
        run: yarn build

      - name: Firebase Hosting sync
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NLW_LETMEASK_55E46 }}'
          channelId: live
          projectId: nlw-letmeask-55e46
